### ISSUE TITLE
queryPurchases NullPointerException

### ISSUE THREAD

**Issue by ZerozAndOnes** [dooboolab/react-native-iap#1034]
### Version of react-native-iap
4.4.0

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Doesn't crash

### Actual behavior
```
Crashes occasionally with
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.billingclient.api.Purchase$PurchasesResult com.android.billingclient.api.BillingClient.queryPurchases(java.lang.String)' on a null object reference
       at com.dooboolab.RNIap.RNIapModule$11.run(RNIapModule.java:575)
       at com.dooboolab.RNIap.RNIapModule.ensureConnection(RNIapModule.java:91)
       at com.dooboolab.RNIap.RNIapModule.sendUnconsumedPurchases(RNIapModule.java:569)
       at com.dooboolab.RNIap.RNIapModule.startListening(RNIapModule.java:596)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:919)
```

### Tested environment (Emulator? Real Device?)
Real Device in production

### Steps to reproduce the behavior
Unable to reproduce. We possibly require a null check for BillingClient before calling queryPurchases for the devices that have an issue with it.

**Comment by hyochan** [comment]
Could you try `4.5.0` and come back?

**Comment by ZerozAndOnes** [comment]
Will give it a go, if the issue pops again after release, will update you.
Thanks 😄

**Comment by howg0924** [comment]
@hyochan I would like to update. We still experienced this crash on RNIap 4.5.2 on real devices in production:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.billingclient.api.Purchase$PurchasesResult com.android.billingclient.api.BillingClient.queryPurchases(java.lang.String)' on a null object reference
       at com.dooboolab.RNIap.RNIapModule$11.run(RNIapModule.java:575)
       at com.dooboolab.RNIap.RNIapModule.ensureConnection(RNIapModule.java:91)
       at com.dooboolab.RNIap.RNIapModule.sendUnconsumedPurchases(RNIapModule.java:569)
       at com.dooboolab.RNIap.RNIapModule.startListening(RNIapModule.java:596)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:169)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by haozhutw** [comment]
I have same issue in my production app, I'm using `react-native-iap@4.1.0`, here is the crash log:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.billingclient.api.Purchase$PurchasesResult com.android.billingclient.api.BillingClient.queryPurchases(java.lang.String)' on a null object reference
       at com.dooboolab.RNIap.RNIapModule.onPurchasesUpdated(RNIapModule.java:542)
       at com.dooboolab.RNIap.RNIapModule$11.run(RNIapModule.java:596)
       at com.dooboolab.RNIap.RNIapModule.ensureConnection(RNIapModule.java:97)
       at com.dooboolab.RNIap.RNIapModule.sendUnconsumedPurchases(RNIapModule.java:579)
       at com.dooboolab.RNIap.RNIapModule.startListening(RNIapModule.java:606)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:223)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by medonagy45** [comment]
I am having the same issue on version 5.2.13 here is the crash log
`java.lang.NullPointerException: 
  at com.dooboolab.RNIap.RNIapModule$13.run (RNIapModule.java:20)
  at com.dooboolab.RNIap.RNIapModule.ensureConnection (Unknown Source:10)
  at com.dooboolab.RNIap.RNIapModule.sendUnconsumedPurchases (Unknown Source:5)
  at com.dooboolab.RNIap.RNIapModule.startListening (Unknown Source)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (Unknown Source:149)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (Unknown Source:21)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (Unknown Source)
  at android.os.Looper.loop (Looper.java:237)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (Unknown Source:37)
  at java.lang.Thread.run (Thread.java:919)`

**Comment by roots-ai** [comment]
Any updates here?
