### ISSUE TITLE
java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by MidnightCoke** [dooboolab/react-native-iap#1050]
### Version of react-native-iap
"react-native-iap": "^4.5.0",
### Version of react-native
"react": "16.11.0",
 "react-native": "0.62.2",
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
get subscriptions
### Actual behavior
crash error
### Tested environment (Emulator? Real Device?)
both
### Steps to reproduce the behavior
- follow readme for setup
- call getSubscriptions() method
- you will get this crash

```
07-21 08:36:16.287 18351 18351 E AndroidRuntime: FATAL EXCEPTION: main
07-21 08:36:16.287 18351 18351 E AndroidRuntime: Process: mypackagename.hidden.hidden, PID: 18351
07-21 08:36:16.287 18351 18351 E AndroidRuntime: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:102)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at com.dooboolab.RNIap.RNIapModule$5.run(RNIapModule.java:234)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at com.dooboolab.RNIap.RNIapModule$2.onBillingSetupFinished(RNIapModule.java:104)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection$1.run(BillingClientImpl.java:1521)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-21 08:36:16.287 18351 18351 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by haliliceylan** [comment]
i have same issue

**Comment by MidnightCoke** [comment]
Sorry guys its typo

**Comment by aadityapaliwal94** [comment]
@MidnightCoke What do you mean by type? I am facing this issue after RN update.
