### ISSUE TITLE
RN.RNIap.buyProduct() Android Error

### ISSUE THREAD

**Issue by simpleblack** [dooboolab/react-native-iap#114]
### Version of react-native-iap
react-native: 0.54.4
react-native-iap: 0.3.5

### Expected behavior

This is fabric error log
Android alpha test

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.content.ComponentName.<init>(ComponentName.java:128)
       at android.content.Intent.<init>(Intent.java:5359)
       at com.android.billingclient.api.BillingClientImpl.launchBillingFlow(BillingClientImpl.java:365)
       at com.dooboolab.RNIap.RNIapModule.buyItemByType(RNIapModule.java:272)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:762)
```
### Actual behavior
```javascript
onPressByProduct = async(productId) => {
    try {
      const purchase = await RNIap.buyProduct(productId)
    } catch (err) {
      Alert.alert(err.message)
    }
  }
```
### Steps to reprodue the behabior

In my case getProducts success.
I get an error when I run buyProduct.

**Comment by dooboolab** [comment]
@simpleblack Sorry for this one. This should be fixed earlier but the code wasn't merged properly from the previous version. So could you please use version `0.3.6`? This should be fixed.

**Comment by simpleblack** [comment]
0.3.7 Error
```
Fatal Exception: com.facebook.react.common.JavascriptException: Can't find variable: consumeProduct, stack:
<unknown>@779:1599
d@2:768
n@2:409
t@2:262
<unknown>@778:156
d@2:768
n@2:409
t@2:262
<unknown>@561:5558
d@2:768
n@2:409
t@2:262
<unknown>@358:421
d@2:768
n@2:409
t@2:262
<unknown>@303:348
d@2:768
n@2:409
t@2:262
<unknown>@12:42
d@2:768
n@2:339
t@2:262
global code@781:8

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by dooboolab** [comment]
@simpleblack Yes. I've also seen this. There was some issue in PR. So I am fixing it. `0.3.9` will work fine. Sorry man~.

**Comment by simpleblack** [comment]
@dooboolab Thanks.
