### ISSUE TITLE
error: Error: Unable to resolve module `./type/apple` from `node_modules/react-native-iap/index.js`:

### ISSUE THREAD

**Issue by sayem314** [dooboolab/react-native-iap#1238]
### Version of react-native-iap

5.2.4

### Platforms you faced the error (IOS or Android or both?)

Both

### Expected behavior

Should work fin

### Actual behavior

Error screen

### Tested environment (Emulator? Real Device?)

Emulator

### Steps to reproduce the behavior

Just import the module and run on dev. V5.2.3 works fine btw.

**Comment by nikita-bekish** [comment]
same here

**Comment by madandrija** [comment]
Same here

**Comment by exentrich** [comment]
same here

**Comment by summonerriftofficial** [comment]
same herer

**Comment by summonerriftofficial** [comment]
error: Error: Unable to resolve module `./type/apple` from `node_modules/react-native-iap/index.js`: 

None of these files exist:
  * node_modules/react-native-iap/type/apple(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/react-native-iap/type/apple/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ahmedsafadi/Desktop/copycatt-rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

**Comment by hyochan** [comment]
Hi! Thanks for the report! Could you kindly try `5.2.5` and come back?

**Comment by sayem314** [comment]
Yes working now. Thanks!

**Comment by madandrija** [comment]
@hyochan I'm getting this error again after upgrading from 5.2.6 to 5.2.11

**Comment by hyochan** [comment]
@madandrija Shouldn't happen. I may forgot prebuild so I've published again in `5.2.12`. Please try this and if this still happens, try to remove `node_modules` and re-install it.

**Comment by madandrija** [comment]
Works now, had to start with `npm start -- --reset-cache`
