### ISSUE TITLE
 [8.0.1] [AmazonFireTv] App crashes on startup

### ISSUE THREAD

**Issue by spakanati123** [dooboolab/react-native-iap#1643]
**Version of react-native-iap**
8.0.1

**Version of react-native**
react-native: 0.66.3

**Platforms you faced the error (IOS or Android or both?)**
Amazon(android)

Expected behavior
App should launch with out crashes

**Actual behavior**
App is crashing

 **Tested environment (Emulator? Real Device?)**
Real Device

**Note:** Issue reproducing alway on 0.66.3 RN of release build and on debug build very few times observed crash.
Our application earlier version running on 0.63 and did not observe any crash for same react-native-iap version.

 
 **Steps to reproduce the behavior**

[adb_logcat.log](https://github.com/dooboolab/react-native-iap/files/8054562/adb_logcat.log)

```
07-13 15:17:18.504 15857 15857 E AndroidRuntime: FATAL EXCEPTION: main
07-13 15:17:18.504 15857 15857 E AndroidRuntime: Process: com.addiction_free_video_rn, PID: 15857
07-13 15:17:18.504 15857 15857 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.addiction_free_video_rn/com.addiction_free_video_rn.MainActivity}: java.lang.IllegalStateException: You must register a PurchasingListener before invoking this operation
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3608)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3648)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2889)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6523)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
07-13 15:17:18.504 15857 15857 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You must register a PurchasingListener before invoking this operation
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.amazon.device.iap.internal.d.e(PurchasingManager.java:51)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.amazon.device.iap.internal.d.c(PurchasingManager.java:68)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.amazon.device.iap.PurchasingService.getUserData(PurchasingService.java:71)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.dooboolab.RNIap.RNIapAmazonModule$1.onHostResume(RNIapAmazonModule.java:38)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:719)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:623)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:580)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.facebook.react.ReactDelegate.onHostResume(ReactDelegate.java:53)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:99)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:7117)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3583)
07-13 15:17:18.504 15857 15857 E AndroidRuntime:        ... 10 more
```

![device-2022-02-13-031248](https://user-images.githubusercontent.com/14059718/153729397-528a93d5-e9df-4581-afe7-9f486f295edb.png)

**Comment by mandrewsan** [comment]
@spakanati123 Did you find a resolution to this? I began facing the same issue for my Amazon build after upgrading.

**Comment by mansilaad19** [comment]
@spakanati123  I am also facing same issue.Did you find any solution?

Version of react-native-iap - 8.0.1
