### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION with android.test.canceled

### ISSUE THREAD

**Issue by martnst** [dooboolab/react-native-iap#177]
### Version of react-native-iap
1.0.6

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
no crash, instead fail gracefully

### Actual behavior
crash in android native module

### Tested environment (Emulator? Real Device?)
Device: Motoralo Moto G4

### Steps to reproduce the behavior
Testing my app with test iap id `android.test.canceled` I get the following crash after android tells me the purchase was successful. 

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.myapp.debug, PID: 15033
                  java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
                      at com.dooboolab.RNIap.RNIapModule$7.onPurchasesUpdated(RNIapModule.java:379)
                      at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
                      at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
                      at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
                      at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

Eventhough there might be actually sth. going wrong I would expect `com.dooboolab.RNIap.RNIapModule` to fail gracefully instead of crashing. 

Thx

**Comment by dooboolab** [comment]
@martnst I haven't tried this one. I'll come back to you if I try this.

**Comment by yasheshkt** [comment]
Even I am facing the same issue with **android.test.canceled**.

**Comment by dooboolab** [comment]
@martnst @yasheshkt Sorry for late come back guys. I was really busy these days. Could you please try `1.0.8`? I've just tested this out and found out there purchases could be null when `buyProduct`. Please reopen when it is still crashing in `1.0.8`. Thank you for the report!

**Comment by martnst** [comment]
@dooboolab thanks for the quick fix. It working fine for me now.
