### ISSUE TITLE
Amazon began crashing on app start

### ISSUE THREAD

**Issue by mandrewsan** [dooboolab/react-native-iap#1865]
**Description**

In release mode, only when building for Amazon, the app crashes as soon as it starts. In debug mode, an error screen is shown, but can be bypassed, and the app will run fine. The main error says: 

```
java.lang.IllegalStateException: You must register a PurchasingListener before invoking this operation
```
This error occurs even after removing all imports to the module in source. It only goes away if I completely uninstall the package.

I can also confirm this happens when setting up a brand new project and then adding react-native-iap after confirming the project works on its own.

**Expected Behavior**

Was working fine previously, I believe I was using version 7.5.0; may have seen issues after 8.2.1, though I also upgraded React Native and enabled Hermes. Still works fine on iOS and Android.

**Environment:**

- react-native-iap: 9.0.1
- react-native: 0.69.2
- Platforms (iOS, Android, emulator, simulator, device): Amazon, real device (Kindle Fire)

**To Reproduce**

1. Install react-native-iap
2. Build for Amazon
3. Error is shown in debug; app crash in release

---

![Screenshot_20220816-151035](https://user-images.githubusercontent.com/7074353/184994242-0bcedd37-9e55-4623-aabf-c5355e75059c.png)

[Optional] **Additional Context**

```
2022-08-16 14:22:06.758 3111-3111/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: [package_name], PID: 3111
    java.lang.IllegalStateException: You must register a PurchasingListener before invoking this operation
        at com.amazon.device.iap.internal.d.e(PurchasingManager.java:51)
        at com.amazon.device.iap.internal.d.c(PurchasingManager.java:68)
        at com.amazon.device.iap.PurchasingService.getUserData(PurchasingService.java:71)
        at com.dooboolab.RNIap.RNIapAmazonModule$lifecycleEventListener$1.onHostResume(RNIapAmazonModule.kt:135)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:272)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:780)
        at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:815)
        at com.facebook.react.ReactInstanceManager.access$1700(ReactInstanceManager.java:136)
        at com.facebook.react.ReactInstanceManager$6.run(ReactInstanceManager.java:1199)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:6752)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1867

**Comment by andresesfm** [comment]
Fix published on `9.0.3`

**Comment by mandrewsan** [comment]
Thank you! I can confirm this error is no longer showing up for me.

**Comment by CalNicklin** [comment]
This error has popped up again on 12.10.8
