### ISSUE TITLE
import IAP but got undefined

### ISSUE THREAD

**Issue by RocMark** [dooboolab/react-native-iap#1962]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
upgrade to v11.0.0-rc.1, import IAP getting IAP undefined.
works fine when using v9.0.0-rc.4.
i had follow the migrate docs. https://github.com/dooboolab/react-native-iap/blob/next/docs/docs/migrate_to_11.0.0.md
not sure what i missed.

```
// is there a way to check whether user canMakePayment ?

// In ios it will check whether user canMakePayment.
export declare const initConnection: () => Promise<boolean>;
```

**Expected Behavior**
same as ^9.0.0-rc.4

**Screenshots**
```
TypeError: undefined is not an object (evaluating '_reactNativeIap.default.getProducts')

This error is located at:
    in Offer (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by UserNavigator)
    in UserNavigator (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenNavigationContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by AppNavigator)
    in AppNavigator (created by Router)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Router)
    in TouchableWithoutFeedback (created by Router)
    in PortalProvider (created by Router)
    in Router (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in RCTView (created by View)
    in View (created by BaseLayout)
    in RCTView (created by View)
    in View (created by BaseLayout)
    in BaseLayout (created by App)
    in $29383e587d62412a$export$9f8ac96af4b1b2ae (created by NativeBaseProvider)
    in ToastProvider (created by NativeBaseProvider)
    in PortalProvider (created by NativeBaseProvider)
    in HybridProvider (created by NativeBaseProvider)
    in ResponsiveQueryProvider (created by NativeBaseProvider)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by NativeBaseProvider)
    in NativeBaseConfigProviderProvider (created by NativeBaseProvider)
    in NativeBaseProvider (created by App)
    in $29383e587d62412a$export$9f8ac96af4b1b2ae (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

**Environment:**

- react-native-iap: 11.0.0-rc.1
- react-native: 0.68.2
- Platforms: iOS  (expo internal build)

**To Reproduce**

```
npm install react-native-iap@next

// App.js
import IAP from 'react-native-iap'

useEffect(() => {
  console.log('===IAP===', IAP) // undefined
  if (Platform.OS === 'ios') { 
     IAP.getProducts([]).then((products) => {
      console.log('===getProducts===', products)
    })
  }
}, [])
```
---

[Optional] **Additional Context**
thanks for the works you guys do. excited to see Store Kit2 got supported !

**Comment by nes123** [comment]
It seems that you need to import * as IAP
It got changed again?! the syntax is very different in general could not make it to work yet.

**Comment by andresesfm** [comment]
To upgrade from 9 -> 11 please implement the changes detailed here: https://github.com/dooboolab/react-native-iap/blob/next/docs/docs/migrate_to_10.0.0.md followed by the changes detailed here: https://github.com/dooboolab/react-native-iap/blob/next/docs/docs/migrate_to_11.0.0.md
