### ISSUE TITLE
Crash due to IllegalArgumentException

### ISSUE THREAD

**Issue by taschik** [dooboolab/react-native-iap#2103]
**Description**

Found the following crash for Android in our Sentry:

```
java.lang.IllegalArgumentException: Product list cannot be empty.
    at com.android.billingclient.api.QueryProductDetailsParams$Builder.setProductList(com.android.billingclient:billing@@5.0.0:2)
    at com.dooboolab.RNIap.RNIapModule$getItemsByType$1.invoke(RNIapModule.kt:214)
    at com.dooboolab.RNIap.RNIapModule$getItemsByType$1.invoke(RNIapModule.kt:200)
    at com.dooboolab.RNIap.RNIapModule.ensureConnection(RNIapModule.kt:59)
    at com.dooboolab.RNIap.RNIapModule.getItemsByType(RNIapModule.kt:200)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:1012)
```

**Expected Behavior**

An empty product list, due to a failed network request or any other reason should not crash the app.

**Environment:**

- react-native-iap: 12.1.2
- react-native: 66.4
- Platforms (iOS, Android, emulator, simulator, device): Android

**Comment by andresesfm** [comment]
It shouldn't crash but this is most likely a developer error. Skus are not being passed to the method

**Comment by andresesfm** [comment]
Fix here: https://github.com/dooboolab/react-native-iap/pull/2105

**Comment by andresesfm** [comment]
Released as `12.4.3`

**Comment by taschik** [comment]
Thank you @andresesfm for the quick fix!
