### ISSUE TITLE
Buying a subscription fails with a Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by 7kfpun** [dooboolab/react-native-iap#276]
### Version of react-native-iap
react-native-iap: 2.2.2
react-native: 0.47.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Purchase successfully

### Actual behavior
Buying a subscription fails with a runtime exception:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
       at com.dooboolab.RNIap.RNIapModule$11.onPurchasesUpdated(RNIapModule.java:413)
       at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
       at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
       at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
       at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Tested environment (Emulator? Real Device?)
Real device (signed APK)

### Steps to reproduce the behavior

await RNIap.initConnection();
await RNIap.getProducts(itemSkus);
await RNIap.buySubscription(product.productId);

**Comment by dooboolab** [comment]
Anyone else experiencing this?

**Comment by 7kfpun** [comment]
It happens while using buySubscription with products (instead of subscriptions).
