### ISSUE TITLE
App crashes after buyProduct on Android

### ISSUE THREAD

**Issue by theoryweary** [dooboolab/react-native-iap#329]
### Version of react-native-iap
2.3.19",
  "react-native": "0.57.1",
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
App returns to foreground after completing a purchase
### Actual behavior
App crashes after completing a purchase.  The purchase is successful and exists after restarting the app, but the app should not crash.
### Tested environment (Emulator? Real Device?)
Real Device, signed through the Play Store. Waited 48 hours after creating app/subscription on Play Store
### Steps to reproduce the behavior
Run   InAppPurchase.buyProduct('subscriptionID').then(purchase => { 
//   dispatch action
              }).catch(err => {
                console.warn(err); // standardized err.code and err.message available
              })

### In Android Studio, I see this error:

2018-11-29 22:17:19.167 1942-4776/? D/ConnectivityService: filterNetworkStateForUid() uid: 10017 networkInfo: [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "TheGreatOutdoors", failover: false, available: true, roaming: false, metered: false]
2018-11-29 22:17:19.175 14121-14129/? E/System: Uncaught exception thrown by finalizer
2018-11-29 22:17:19.176 14121-14129/? E/System: java.lang.IllegalStateException: Binder has been finalized!
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:761)
        at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1449)
        at android.security.KeyStore.abort(KeyStore.java:971)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:744)
        at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(Unknown Source:0)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)

###  Thank you!!

**Comment by dooboolab** [comment]
Well looks weird because it isn't crashing in the example project. Can you try that first and see what you've done differently?

**Comment by theoryweary** [comment]
Thanks for the quick response!

I just copied the iapExample/src folder into my react-native project and imported the app.js as my new entry point so that my app only uses the example stack navigator, first and second page. I'm now able to run the app and use the example screens to list my purchases and attempt to purchase my subscription.  Unfortunately I'm still getting the same error.

As far as I can tell my Android files are configured just like the example (dependency listed in build.gradle, permission added to AndroidManifest, import added to MainApplication.java).  My only guess is that my dependencies are causing some sort of issue?  Here's my Dependencies in package.json:

"dependencies": {
    "buffer": "^5.2.1",
    "moment": "^2.22.2",
    "native-base": "^2.8.1",
    "re-reselect": "^2.2.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-alphabetflatlist": "^1.0.4",
    "react-native-communications": "^2.2.1",
    "react-native-contacts": "^2.2.4",
    "react-native-extended-stylesheet": "^0.10.0",
    "react-native-firebase": "^5.1.0",
    "react-native-iap": "^2.3.19",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-splash-screen": "^3.1.1",
    "react-native-uuid": "^1.4.9",
    "react-navigation": "^2.18.0",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "reselect": "^4.0.0"
  }

Where else should I look?

Thanks again!!!

**Comment by dooboolab** [comment]
I can't tell looking at it like this. If you find yourself trouble with other packages, it would be good to install them one by one and see which causes the problem.

**Comment by theoryweary** [comment]
Hi, I just did more troubleshooting and reran the stack trace in Android Studio. I'm pretty sure that the error is actually coming from RNIapModule.java:430.   Here's the full stack trace:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: bundleID, PID: 433
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at com.dooboolab.RNIap.RNIapModule$11.onPurchasesUpdated(RNIapModule.java:430)
        at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
        at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
        at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
        at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Please consider reopening this - looks like the issue is with this library.

Thanks again
