### ISSUE TITLE
`requestPurchase` throws "Attempt to invoke 'java.util.List.iterator()' on a null object reference on Android"

### ISSUE THREAD

**Issue by myklam** [dooboolab/react-native-iap#515]
### Version of react-native-iap
3.0.0-rc.2
### Version of react-native
0.58.6
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Calling `requestPurchase` should bring up prompt to buy item. `consumeAllItemsAndroid` should work.
### Actual behavior
With `requestPurchase` the app crashes with the error:
```
Attempt to invoke interface method 'java.util.Iterator Java.util.List.iterator()' on a null object reference
```

With `consumeAllItemsAndroid` the function fails silently

### Tested environment (Emulator? Real Device?)
Real device: Samsung Note 9
### Steps to reproduce the behavior

I'm doing all of set up/interactions with react-native-iap from within a mobx store, but have tried implementing directly in the component, like the example app, but I get the same issue.

Here's my functions:
```
@action
  setPurchaseListener = async () => {
    try {
      const result = await RNIap.initConnection();
      await RNIap.consumeAllItemsAndroid();
    } catch (err) {
      console.tron.error(err);
    }

    this.purchaseListener = purchaseUpdatedListener(purchase => {
      console.tron.log('purchase', purchase);
    });
    console.tron.log("this.purchaseListener", this.purchaseListener);
  };

  @action
  removePurchaseListener = () => {
    if (this.purchaseListener) {
      this.purchaseListener.remove();
      this.purchaseListener = null;
    }
  };

  @action
  buy = async () => {
    try {
      RNIap.requestPurchase('android.test.purchased');
    } catch (err) {
      console.tron.error(err.code, err.message);
    }
  };
``` 

I'm calling `setPurchaseListener` in `componentDidMount`, `removePurchaseListener` in `componentWillMount`, and `buy` is called in the `onPress` of a button.

**Comment by hyochan** [comment]
@myklam Could you kindly add `adb logcat` so I can dig in that line and get more idea?

**Comment by myklam** [comment]
Yeah sure, here's the logcat output for the error:
```
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: Exception in native call
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.dooboolab.RNIap.RNIapModule$8.run(RNIapModule.java:351)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.dooboolab.RNIap.RNIapModule.ensureConnection(RNIapModule.java:86)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.dooboolab.RNIap.RNIapModule.buyItemByType(RNIapModule.java:323)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
06-12 10:57:41.269  9284  9387 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
06-12 10:57:41.309  9284  9284 D ReactNative: CatalystInstanceImpl.destroy() start
06-12 10:57:41.312  9284  9284 W unknown:ReactNative: Calling JS function after bridge has been destroyed: JSTimers.callTimers([[152]])
06-12 10:57:41.320  9284  9322 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
06-12 10:57:41.572  9284  9331 D ReactNative: CatalystInstanceImpl.destroy() end
06-12 10:57:41.659  9284  9284 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
06-12 10:57:42.177  9284  9480 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["Sentry/eventStored",{}])
06-12 10:57:42.177  9284  9480 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["Sentry/eventSentSuccessfully",{"tags":{"react":"true","environment":"development"},"extra":{"react":true,"session:duration":7927,"environment":"development"},"dist":"142","release":"com.test.debug-2.0.162","message":"undefined is not a function (evaluating 'TestStore.buy()')","level":"fatal","event_id":"baa03ffa-6eed-4494-9632-2a899422a07f"}])
06-12 10:57:45.563  9284  9284 W unknown:ReactNative: Calling JS function after bridge has been destroyed: JSTimers.callTimers([[24]])
06-12 10:57:57.006  9284  9284 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["appStateDidChange",{"app_state":"background"}])
```

**Comment by myklam** [comment]
Also, doing just a little bit of debugging it seems like my call to `purchaseUpdatedListener` is not completing successfully.

**Comment by hyochan** [comment]
@myklam I'll try to go over this in weekend. Also, I'd like you to try `3.0.0-rc.4` and also see what is coming in `purchaseErrorListener`.

**Comment by hyochan** [comment]
Hope `3.0.0-rc.14` can resolve this.

**Comment by myklam** [comment]
@hyochan , sorry, I had to revert to v2, because the project couldn't really wait. I'll try upgrading when I get a few minutes and check the status.

**Comment by varungupta85** [comment]
@hyochan I recently started using this library to add IAPs to my app. I installed `v3.0.0` and followed the instructions and I am observing same error as @myklam when I called `requestPurchase`.

```java
2019-06-21 13:10:17.043 6020-6352/com.myapp E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.dooboolab.RNIap.RNIapModule$8.run(RNIapModule.java:406)
        at com.dooboolab.RNIap.RNIapModule.ensureConnection(RNIapModule.java:87)
        at com.dooboolab.RNIap.RNIapModule.buyItemByType(RNIapModule.java:378)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:761)
```

I have previously tried `v2` as well which I was able to use successfully.

Below is the code flow.

Call this on root component `componentDidMount`
```js
    RNIap.initConnection().then(result =>
      console.tron.log('Successful connection to billing ' + result) // I am able to see this log as true
    )

    purchaseUpdatedListener(purchase => {
      console.tron.log('purchaseUpdatedListener', purchase)
    })

    purchaseErrorListener(error => {
      console.tron.log('purchaseErrorListener', error)
      logError(error, 'Error while purchasing IAP')
    })
```

Call this while trying to purchase item
```js
try {
      RNIap.requestPurchase(Constants.PREMIUM_UPGRADE_SKU)
    } catch (err) {
      logError(err, 'Unable to purchase')
    }
```

`purchaseErrorListener` doesn't log any error as I think it is never invoked.

**Comment by varungupta85** [comment]
@hyochan If I make a call to the `getProducts` API after `initConnection`, then I don't see the error. Is it required to make a call to `getProducts` before calling `requestPurchase`?
