### ISSUE TITLE
NullPointerException in Android

### ISSUE THREAD

**Issue by lachtos** [dooboolab/react-native-iap#600]
I had an app crash in the pre-launch test in google play console, giving this error stack:
```
FATAL EXCEPTION: mqt_native_modules
java.lang.NullPointerException
	at com.dooboolab.RNIap.RNIapModule$11.run(RNIapModule.java:496)
	at com.dooboolab.RNIap.RNIapModule.ensureConnection(RNIapModule.java:89)
	at com.dooboolab.RNIap.RNIapModule.sendUnconsumedPurchases(RNIapModule.java:491)
	at com.dooboolab.RNIap.RNIapModule.startListening(RNIapModule.java:508)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:176)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	at java.lang.Thread.run(Thread.java:841)
```

I don't get crashes yet on real devices, but since the code which caused this crash is fairly new (RNIapModule.java:496) I think it would be smart to take a look into this. Maybe it's just an environment issue and would not occur in real devices?

Also, I just had another pre-launch test on updated apk with no changes to the IAP module/code on the same android 4.3 device and it did not crash.

### Version of react-native-iap
3.3.1

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
Android 4.3 | Galaxy S3

### Expected behavior
No crash

### Actual behavior
java.lang.NullPointerException

### Tested environment (Emulator? Real Device?)
Google Play Console Pre-launch report

### Steps to reproduce the behavior
Have google play console run a pre-launch test on the uploaded app

**Comment by hyochan** [comment]
Please try `3.3.3` and come back.

**Comment by lachtos** [comment]
I have a few crashes because of null pointer at line 504 now, on Android 8.1 in production build

**Comment by hyochan** [comment]
@lachtos Would you try `3.3.5`? It's hard for me to debug since I can't generate this right now.

**Comment by lachtos** [comment]
I can't reproduce it so it's a bit hard to debug. These logs are from google play console crash reports. After some googling I found that there are some rare cases when the value returned from the google api is null, so there should be null checks like there are right now in 3.3.5

I can't afford to keep testing this in production so I threw the code inside a try/catch for now.
