### ISSUE TITLE
Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by schumannd** [dooboolab/react-native-iap#641]
### Version of react-native-iap

2.4.1

### Version of react-native

0.58.6

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Shouldn't error / crash

### Actual behavior

Does error / crash

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

?

This error was caught by our monitoring system.
Stacktrace:

Error: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
  at createErrorFromErrorData(node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:146:36)
  at ? (node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:31)
  at __callImmediates(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:92:36)
  at DebuggerInternal(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
  at this(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:329:14)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:5)

A quick search has led me [to this article](https://stackoverflow.com/questions/35004908/java-for-android-null-pointer-exception-on-iinappbillingservice-getskudetails) but I haven't looked any further into it.

**Comment by hyochan** [comment]
This is fixed in a recent version of `react-native-iap`. Please update or you should have to check the `null` case yourself. Please add null check where you call `getPurchases` in `RNIapModule.java`.

**Comment by schumannd** [comment]
Great to hear that this is fixed, will update!
