### ISSUE TITLE
After eject my expo project, and link, Build fail

### ISSUE THREAD

**Issue by openmaya** [dooboolab/react-native-iap#750]
### Version of react-native-iap
"react-native-iap": "^4.0.0-rc5",

### Version of react-native
"react-native": "https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz",

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Build Success

### Actual behavior
Build Fail

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
After ejecting, AndroidManifest.xml has duplicated configuration such as
>      <uses-permission android:name="android.permission.INTERNET" />
I removed it.

And then faced application configuration problem
gradle guided me to add below and do it
>  <application tools:replace="android:appComponentFactory" android:appComponentFactory="whateverString"

And try again 
>./gradlew buildRelease --stacktrace

full error is below

> Task :app:transformClassesAndResourcesWithProguardForRelease FAILED

> Caused by: java.io.IOException: Can't write [/Users/MyRoot/MyProject/android/app/build/intermediates/transforms/proguard/release/0.jar] (Can't read [/Users/MyRoot/.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/bf0093a2cc4d2c88ed4d1924a4e693d5/jars/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [android/support/v4/app/v$a$a.class]))
        at proguard.OutputWriter.writeOutput(OutputWriter.java:202)
        at proguard.OutputWriter.execute(OutputWriter.java:89)
        at proguard.ProGuard.writeOutput(ProGuard.java:515)
        at proguard.ProGuard.execute(ProGuard.java:210)
        at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:66)
        at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:274)
        at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:67)
        at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:178)
        at com.android.builder.tasks.Job.runTask(Job.java:47)
        at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:282)
Caused by: java.io.IOException: Can't read [/Users/MyRoot/.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/bf0093a2cc4d2c88ed4d1924a4e693d5/jars/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [android/support/v4/app/v$a$a.class])
        at proguard.InputReader.readInput(InputReader.java:214)
        at proguard.InputReader.readInput(InputReader.java:184)
        at proguard.OutputWriter.writeOutput(OutputWriter.java:191)
        ... 10 more
Caused by: java.io.IOException: Duplicate jar entry [android/support/v4/app/v$a$a.class]
        at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:155)
        at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:120)
        at proguard.io.JarWriter.createOutputStream(JarWriter.java:137)
        at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
        at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
        at proguard.io.ClassDataEntryWriter.createOutputStream(ClassDataEntryWriter.java:93)
        at proguard.io.ExtraDataEntryWriter.createOutputStream(ExtraDataEntryWriter.java:135)
        at proguard.io.IdleRewriter.read(IdleRewriter.java:49)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
        at proguard.io.JarReader.read(JarReader.java:83)
        at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
        at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
        at proguard.InputReader.readInput(InputReader.java:210)
        ... 12 more

**Comment by hyochan** [comment]
I might have to give it a try on `ejected` expo app. I've had tested until `expo` sdk `32` but nothing newer. Please give any other feedback if anyone else has tried this.

However, I believe this problem relies on `linking` new native modules that doesn't belongs to `expo`. @openmaya I recommend you to `link` any other modules and dig into your problem.

**Comment by openmaya** [comment]
@hyochan Ok, I will try to link another module. Thanks
