### ISSUE TITLE
finishTransaction crashes: ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by voxspox** [dooboolab/react-native-iap#851]
### Version of react-native-iap
4.2.1

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
only Android

### Expected behavior
no crash

### Actual behavior
`finishTransaction` crashes App.

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
- `requestSubscription`
- call `finishTransaction` triggered by `purchaseUpdatedListener`

### Stacktrace from adb logcat
```
Exception in native call
java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:101)
	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	at java.lang.Thread.run(Thread.java:761)

```

**Comment by hyochan** [comment]
@voxspox Thank you for the issue report. Could you kindly find the statement where the line of the codes is related to our module (`RNIapModule.java`).

Since I only see the bug in `react.bridge.*` package, I can't help you out further.

**Comment by voxspox** [comment]
This is what I get from the "red screen". Do you have some hint how to get more context info?

**Comment by cgathergood** [comment]
Hey @voxspox I came across your issue looking at something similar. Ensure that you're passing a string value into `requestSubscription` it looks like you're trying to send an object which is converted to a ReadableNativeMap in Java. Hope this is of some help!

**Comment by tanya-marych** [comment]
I had this because I tried to display in alert
Alert.alert('finishTransaction error', ackErr);
but correct is
Alert.alert('finishTransaction error', JSON.stringify(ackErr));

Maybe it is also your problem
And then you can see why it crashes

**Comment by hanishcodebrew** [comment]
I am facing the same issue @voxspox . Have you solved it ?

**Comment by dpossamai** [comment]
This error happened to me because I was calling:

RNIap.requestSubscription('id'); 

twice when the user clicked the "buy" button.
